In [ ]:
# Install the Pandas Library
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Import Library

import pandas as pd

In [ ]:
# Read the csv data file.

df=pd.read_csv("student_performance.csv")
df

,student_id,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,study_hours_per_week,attendance_percentage,math_score,reading_score,writing_score
0,1,female,group B,some high school,free/reduced,none,2,78,45,64.0,54.0
1,2,male,group A,high school,free/reduced,none,3,68,68,82.0,72.0
2,3,male,group A,some college,standard,none,7,79,86,85.0,69.0
3,4,female,group B,bachelor's degree,standard,completed,1,89,72,100.0,100.0
4,5,male,group E,high school,standard,none,3,97,55,62.0,66.0
...,...,...,...,...,...,...,...,...,...,...,...
299,300,female,group E,some college,standard,none,4,71,57,94.0,79.0
300,1,female,group B,some high school,free/reduced,none,2,78,45,64.0,54.0
301,2,male,group A,high school,free/reduced,none,3,68,68,82.0,72.0
302,3,male,group A,some college,standard,none,7,79,86,85.0,69.0
303,4,female,group B,bachelor's degree,standard,completed,1,89,72,100.0,100.0

In [ ]:
#Info
#df.info()
#Use to show the information about the table like how many rows,columns,integers it have

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   student_id                   304 non-null    int64
 1   gender                       304 non-null    object
 2   race_ethnicity               304 non-null    object
 3   parental_level_of_education  303 non-null    object
 4   lunch                        303 non-null    object
 5   test_preparation_course      304 non-null    object
 6   study_hours_per_week         304 non-null    int64
 7   attendance_percentage        304 non-null    int64
 8   math_score                   304 non-null    int64
 9   reading_score                303 non-null    float64
 10  writing_score                303 non-null    float64
dtypes: float64(2), int64(4), object(5)
memory usage: 26.3+ KB

In [ ]:
#Describe()
#Use to describe the important Parameters about the data Its like a Summary Report of the Table
df.describe()

,student_id,study_hours_per_week,attendance_percentage,math_score,reading_score,writing_score
count,304.000000,304.000000,304.000000,304.000000,303.000000,303.000000
mean,148.552632,4.486842,79.513158,75.062500,78.264026,77.930693
std,87.812491,2.343411,9.325070,15.445829,14.930621,14.802625
min,1.000000,1.000000,45.000000,28.000000,35.000000,42.000000
25%,72.750000,2.000000,73.000000,65.000000,69.000000,68.000000
50%,148.500000,4.000000,79.000000,75.500000,81.000000,79.000000
75%,224.250000,7.000000,86.000000,87.000000,89.500000,89.500000
max,300.000000,8.000000,100.000000,100.000000,100.000000,100.000000

In [ ]:
#df.head()
#Use to show the top values of the Row.It shows first five rows by defult but we can mention the numbers also.

df.head()
df.head(2)

,student_id,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,study_hours_per_week,attendance_percentage,math_score,reading_score,writing_score
0,1,female,group B,some high school,free/reduced,none,2,78,45,64.0,54.0
1,2,male,group A,high school,free/reduced,none,3,68,68,82.0,72.0

In [ ]:
#df.tail()
#Used to show the last data of the Dataframe like bottom rows
df.tail()
df.tail(1)
df[1:1]

Empty DataFrame
Columns: [student_id, gender, race_ethnicity, parental_level_of_education, lunch, test_preparation_course, study_hours_per_week, attendance_percentage, math_score, reading_score, writing_score]
Index: []

In [ ]:
#Use to show the columns name of the Data Frame
df.columns[3]

'parental_level_of_education'

In [ ]:
#Use to show the value of the
df.values

array([[1, 'female', 'group B', ..., 45, 64.0, 54.0],
       [2, 'male', 'group A', ..., 68, 82.0, 72.0],
       [3, 'male', 'group A', ..., 86, 85.0, 69.0],
       ...,
       [2, 'male', 'group A', ..., 68, 82.0, 72.0],
       [3, 'male', 'group A', ..., 86, 85.0, 69.0],
       [4, 'female', 'group B', ..., 72, 100.0, 100.0]], dtype=object)

In [ ]:
#Tells about the rows and columns in the dataframe
df.size

3344

In [ ]:
#Tells about the Datatypes
df.dtypes

student_id                       int64
gender                          object
race_ethnicity                  object
parental_level_of_education     object
lunch                           object
test_preparation_course         object
study_hours_per_week             int64
attendance_percentage            int64
math_score                       int64
reading_score                  float64
writing_score                  float64
dtype: object

In [ ]:
#Show Indexes

df.index

RangeIndex(start=0, stop=304, step=1)

In [ ]:
#Delete Values
df.drop(columns=["math_score"])

,student_id,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,study_hours_per_week,attendance_percentage,reading_score,writing_score
0,1,female,group B,some high school,free/reduced,none,2,78,64.0,54.0
1,2,male,group A,high school,free/reduced,none,3,68,82.0,72.0
2,3,male,group A,some college,standard,none,7,79,85.0,69.0
3,4,female,group B,bachelor's degree,standard,completed,1,89,100.0,100.0
4,5,male,group E,high school,standard,none,3,97,62.0,66.0
...,...,...,...,...,...,...,...,...,...,...
299,300,female,group E,some college,standard,none,4,71,94.0,79.0
300,1,female,group B,some high school,free/reduced,none,2,78,64.0,54.0
301,2,male,group A,high school,free/reduced,none,3,68,82.0,72.0
302,3,male,group A,some college,standard,none,7,79,85.0,69.0
303,4,female,group B,bachelor's degree,standard,completed,1,89,100.0,100.0

In [ ]:
#Delete All columns except 5

In [ ]:
df = df.iloc[:, :5]
display(df.head())

   student_id  gender race_ethnicity parental_level_of_education         lunch
0           1  female        group B            some high school  free/reduced
1           2    male        group A                 high school  free/reduced
2           3    male        group A                some college      standard
3           4  female        group B           bachelor's degree      standard
4           5    male        group E                 high school      standard

In [ ]:
df.loc([2,"launch"]=="free")

In [ ]:
df

,student_id,gender,race_ethnicity,parental_level_of_education,lunch
0,1,female,group B,some high school,free/reduced
1,2,male,group A,high school,free/reduced
2,3,male,group A,some college,standard
3,4,female,group B,bachelor's degree,standard
4,5,male,group E,high school,standard
...,...,...,...,...,...
299,300,female,group E,some college,standard
300,1,female,group B,some high school,free/reduced
301,2,male,group A,high school,free/reduced
302,3,male,group A,some college,standard
303,4,female,group B,bachelor's degree,standard

In [ ]:
#Show all the null values
df.isnull().sum()

student_id                     0
gender                         0
race_ethnicity                 0
parental_level_of_education    1
lunch                          1
dtype: int64

In [ ]:
df.isnull()

     student_id  gender  race_ethnicity  parental_level_of_education  lunch
0         False   False           False                        False  False
1         False   False           False                        False  False
2         False   False           False                        False  False
3         False   False           False                        False  False
4         False   False           False                        False  False
..          ...     ...             ...                          ...    ...
299       False   False           False                        False  False
300       False   False           False                        False  False
301       False   False           False                        False  False
302       False   False           False                        False  False
303       False   False           False                        False  False

[304 rows x 5 columns]

In [ ]:
#fillna Values

df["lunch"]=df["lunch"].fillna("free")
df.isnull().sum()

student_id                     0
gender                         0
race_ethnicity                 0
parental_level_of_education    1
lunch                          0
dtype: int64